import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const name = '@openworkers/adapter-sveltekit';

/** @type {import('./index.js').default} */
export default function (options = {}) {
	return {
		name,
		/** @param {import('@sveltejs/kit').Builder} builder */
		async adapt(builder) {
			const dest = options.out ?? 'dist';
			const assetsDir = `${dest}/assets`;

			const files = fileURLToPath(new URL('./files', import.meta.url).href);
			const tmp = builder.getBuildDirectory('openworkers-tmp');

			builder.rimraf(dest);
			builder.mkdirp(dest);
			builder.mkdirp(assetsDir);
			builder.mkdirp(tmp);

			// Write client assets
			builder.writeClient(assetsDir);

			// Write prerendered pages
			builder.writePrerendered(assetsDir);

			// Generate 404.html fallback
			const fallback = path.join(assetsDir, '404.html');
			if (!existsSync(fallback)) {
				writeFileSync(fallback, 'Not Found');
			}

			// Generate manifest
			writeFileSync(
				`${tmp}/manifest.js`,
				`export const manifest = ${builder.generateManifest({ relativePath: path.posix.relative(tmp, builder.getServerDirectory()) })};\n\n` +
					`export const prerendered = new Set(${JSON.stringify(builder.prerendered.paths)});\n\n` +
					`export const base_path = ${JSON.stringify(builder.config.kit.paths.base)};\n`
			);

			// Create entry point that imports server and manifest
			const entryPoint = `${tmp}/entry.js`;
			const serverPath = posixify(path.resolve(builder.getServerDirectory(), 'index.js'));
			const manifestPath = posixify(path.resolve(tmp, 'manifest.js'));

			writeFileSync(
				entryPoint,
				`import { Server } from '${serverPath}';\n` +
					`import { manifest, prerendered, base_path } from '${manifestPath}';\n` +
					`export { Server, manifest, prerendered, base_path };\n`
			);

			// Bundle worker with esbuild
			const workerDest = `${dest}/worker.js`;

			await build({
				entryPoints: [`${files}/worker.js`],
				bundle: true,
				format: 'esm',
				platform: 'browser',
				outfile: workerDest,
				alias: {
					SERVER: entryPoint,
					MANIFEST: entryPoint
				},
				external: ['node:*'],
				minify: false,
				banner: {
					js: `// Generated by ${name}\n`
				}
			});

			builder.log.minor(`Wrote ${workerDest}`);
			builder.log.minor(`Wrote ${assetsDir} (${builder.prerendered.paths.length} prerendered pages)`);
		}
	};
}

/** @param {string} str */
function posixify(str) {
	return str.replace(/\\/g, '/');
}
