import { existsSync, writeFileSync, readdirSync, statSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf-8'));
const name = '@openworkers/adapter-sveltekit';
const version = pkg.version;

/** @type {import('./index.js').default} */
export default function (options = {}) {
  return {
    name,
    /** @param {import('@sveltejs/kit').Builder} builder */
    async adapt(builder) {
      const dest = options.out ?? 'dist';
      const assetsDir = `${dest}/assets`;
      const functionsEnabled = options.functions ?? false;

      const files = fileURLToPath(new URL('./files', import.meta.url).href);
      const tmp = builder.getBuildDirectory('openworkers-tmp');

      builder.rimraf(dest);
      builder.mkdirp(dest);
      builder.mkdirp(assetsDir);
      builder.mkdirp(tmp);

      // Write client assets (returns list of files)
      const clientFiles = builder.writeClient(assetsDir);

      // Write prerendered pages
      builder.writePrerendered(assetsDir);

      // Separate static files from app files
      const appPath = builder.getAppPath();
      const staticFiles = clientFiles.filter((f) => !f.startsWith(appPath));

      // Generate 404.html fallback
      const fallback = path.join(assetsDir, '404.html');

      if (!existsSync(fallback)) {
        writeFileSync(fallback, 'Not Found');
      }

      // Generate manifest
      writeFileSync(
        `${tmp}/manifest.js`,
        `export const manifest = ${builder.generateManifest({ relativePath: path.posix.relative(tmp, builder.getServerDirectory()) })};\n\n` +
          `export const prerendered = new Set(${JSON.stringify(builder.prerendered.paths)});\n\n` +
          `export const base_path = ${JSON.stringify(builder.config.kit.paths.base)};\n`
      );

      // Create entry point that imports server and manifest
      const entryPoint = `${tmp}/entry.js`;
      const serverPath = posixify(path.resolve(builder.getServerDirectory(), 'index.js'));
      const manifestPath = posixify(path.resolve(tmp, 'manifest.js'));

      writeFileSync(
        entryPoint,
        `import { Server } from '${serverPath}';\n` +
          `import { manifest, prerendered, base_path } from '${manifestPath}';\n` +
          `export { Server, manifest, prerendered, base_path };\n`
      );

      // Bundle main worker with esbuild
      const workerDest = `${dest}/_worker.js`;
      const shimAsyncHooks = posixify(path.resolve(files, 'shims/async_hooks.js'));

      await build({
        entryPoints: [`${files}/worker.js`],
        bundle: true,
        format: 'esm',
        platform: 'browser',
        outfile: workerDest,
        alias: {
          SERVER: entryPoint,
          MANIFEST: entryPoint,
          'node:async_hooks': shimAsyncHooks
        },
        external: ['node:*'],
        minify: false,
        banner: {
          js: `// Generated by ${name} v${version}\n`
        }
      });

      // Generate mini-workers for API routes if enabled
      /** @type {Array<{pattern: string, worker: string}>} */
      const functions = [];

      if (functionsEnabled) {
        builder.mkdirp(`${dest}/functions`);

        const serverDir = builder.getServerDirectory();
        const viteManifestPath = path.join(serverDir, '.vite/manifest.json');
        const functionTemplate = posixify(path.resolve(files, 'function-worker.js'));

        if (existsSync(viteManifestPath)) {
          const viteManifest = JSON.parse(readFileSync(viteManifestPath, 'utf-8'));
          const endpoints = extractEndpointsFromManifest(viteManifest, serverDir);

          for (const endpoint of endpoints) {
            const routePattern = endpoint.pattern;
            // Use SvelteKit route syntax for worker filename
            const workerName = endpoint.route.replace(/\//g, '-').replace(/^-/, '') || 'index';
            const workerFile = `functions/${workerName}.js`;

            // Bundle using the template with ENDPOINT alias
            await build({
              entryPoints: [functionTemplate],
              bundle: true,
              format: 'esm',
              platform: 'browser',
              outfile: `${dest}/${workerFile}`,
              alias: {
                ENDPOINT: posixify(endpoint.file),
                'node:async_hooks': shimAsyncHooks
              },
              external: ['node:*'],
              minify: false,
              define: {
                ROUTE_PATTERN: JSON.stringify(endpoint.route)
              },
              banner: {
                js: `// Generated by ${name} v${version} - Function: ${routePattern}\n`
              }
            });

            functions.push({
              pattern: routePattern,
              worker: workerFile
            });

            builder.log.minor(`  Generated function: ${routePattern} → ${workerFile}`);
          }
        }
      }

      // Generate _routes.json for edge routing
      const routes = {
        // Immutable assets (hashed filenames, cache forever)
        immutable: [`/${appPath}/immutable/*`],
        // Static files from /static folder (robots.txt, favicon, etc.)
        static: staticFiles.map((f) => `/${f}`),
        // Prerendered pages (serve from assets, no worker needed)
        prerendered: builder.prerendered.paths,
        // Functions (API routes as separate workers)
        functions: functions,
        // Everything else -> SSR
        ssr: ['/*']
      };

      writeFileSync(
        `${dest}/_routes.json`,
        JSON.stringify(routes, null, 2)
      );

      builder.log.minor(`Wrote ${workerDest}`);
      builder.log.minor(`Wrote ${dest}/_routes.json`);

      if (functions.length > 0) {
        builder.log.minor(`Wrote ${functions.length} function workers to ${dest}/functions/`);
      }

      builder.log.minor(`Wrote ${assetsDir} (${builder.prerendered.paths.length} prerendered pages)`);
    }
  };
}

/**
 * Extract endpoints from Vite manifest and convert SvelteKit routes to simple patterns
 * @param {object} manifest - Vite manifest object
 * @param {string} serverDir - Server build directory
 * @returns {Array<{pattern: string, route: string, file: string}>}
 */
function extractEndpointsFromManifest(manifest, serverDir) {
  const endpoints = [];

  for (const [key, entry] of Object.entries(manifest)) {
    // Only process endpoint files (+server.ts)
    if (!key.includes('+server.ts')) continue;

    const sourcePath = entry.src;
    if (!sourcePath || !sourcePath.startsWith('src/routes/')) continue;

    // Extract route from source path: src/routes/status/[code]/[[reason]]/+server.ts
    const routePart = sourcePath
      .replace(/^src\/routes/, '')
      .replace(/\/\+server\.(ts|js)$/, '');

    // Convert SvelteKit route syntax to simple wildcard patterns
    const pattern = convertRouteToPattern(routePart);

    // Get the built file path
    const file = path.join(serverDir, entry.file);

    endpoints.push({
      pattern,       // For routing: /status/*/*
      route: routePart,  // For filename: /status/[code]/[[reason]]
      file
    });
  }

  return endpoints;
}

/**
 * Convert SvelteKit route syntax to simple wildcard patterns
 * Examples:
 *   /status/[code]/[[reason]] becomes /status/star/star
 *   /range/[n] becomes /range/star
 *   /drip/[...params] becomes /drip/doublestar
 * @param {string} route - SvelteKit route (e.g. "/status/[code]/[[reason]]")
 * @returns {string} - Simple pattern with wildcards
 */
function convertRouteToPattern(route) {
  if (!route || route === '/') return '/';

  const segments = route.split('/').filter(Boolean);
  const patternSegments = segments.map(segment => {
    // Rest parameter: [...params] -> **
    if (segment.startsWith('[...') && segment.endsWith(']')) {
      return '**';
    }

    // Required or optional parameter: [param] or [[param]] -> *
    if ((segment.startsWith('[') && segment.endsWith(']')) ||
        (segment.startsWith('[[') && segment.endsWith(']]'))) {
      return '*';
    }

    // Static segment: keep as-is
    return segment;
  });

  return '/' + patternSegments.join('/');
}

/** @param {string} str */
function posixify(str) {
  return str.replace(/\\/g, '/');
}
