import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const name = '@openworkers/adapter-sveltekit';

/** @type {import('./index.js').default} */
export default function (options = {}) {
  return {
    name,
    /** @param {import('@sveltejs/kit').Builder} builder */
    async adapt(builder) {
      const dest = options.out ?? 'dist';
      const assetsDir = `${dest}/assets`;

      const files = fileURLToPath(new URL('./files', import.meta.url).href);
      const tmp = builder.getBuildDirectory('openworkers-tmp');

      builder.rimraf(dest);
      builder.mkdirp(dest);
      builder.mkdirp(assetsDir);
      builder.mkdirp(tmp);

      // Write client assets (returns list of files)
      const clientFiles = builder.writeClient(assetsDir);

      // Write prerendered pages
      builder.writePrerendered(assetsDir);

      // Separate static files from app files
      const appPath = builder.getAppPath();
      const staticFiles = clientFiles.filter((f) => !f.startsWith(appPath));

      // Generate 404.html fallback
      const fallback = path.join(assetsDir, '404.html');
      if (!existsSync(fallback)) {
        writeFileSync(fallback, 'Not Found');
      }

      // Generate manifest
      writeFileSync(
        `${tmp}/manifest.js`,
        `export const manifest = ${builder.generateManifest({ relativePath: path.posix.relative(tmp, builder.getServerDirectory()) })};\n\n` +
          `export const prerendered = new Set(${JSON.stringify(builder.prerendered.paths)});\n\n` +
          `export const base_path = ${JSON.stringify(builder.config.kit.paths.base)};\n`
      );

      // Create entry point that imports server and manifest
      const entryPoint = `${tmp}/entry.js`;
      const serverPath = posixify(path.resolve(builder.getServerDirectory(), 'index.js'));
      const manifestPath = posixify(path.resolve(tmp, 'manifest.js'));

      writeFileSync(
        entryPoint,
        `import { Server } from '${serverPath}';\n` +
          `import { manifest, prerendered, base_path } from '${manifestPath}';\n` +
          `export { Server, manifest, prerendered, base_path };\n`
      );

      // Bundle worker with esbuild
      const workerDest = `${dest}/worker.js`;
      const shimAsyncHooks = posixify(path.resolve(files, 'shims/async_hooks.js'));

      await build({
        entryPoints: [`${files}/worker.js`],
        bundle: true,
        format: 'esm',
        platform: 'browser',
        outfile: workerDest,
        alias: {
          SERVER: entryPoint,
          MANIFEST: entryPoint,
          'node:async_hooks': shimAsyncHooks
        },
        external: ['node:*'],
        minify: false,
        banner: {
          js: `// Generated by ${name}\n`
        }
      });

      // Generate routes.js for edge routing
      const routes = {
        // Immutable assets (hashed filenames, cache forever)
        immutable: [`/${appPath}/immutable/*`],
        // Static files from /static folder (robots.txt, favicon, etc.)
        static: staticFiles.map((f) => `/${f}`),
        // Prerendered pages (serve from assets, no worker needed)
        prerendered: builder.prerendered.paths,
        // Everything else -> SSR
        ssr: ['/*']
      };

      writeFileSync(
        `${dest}/routes.js`,
        `// Generated by ${name}\n` +
          `// Used by OpenWorkers edge router to bypass worker for static content\n\n` +
          `export default ${JSON.stringify(routes, null, '\t')};\n`
      );

      builder.log.minor(`Wrote ${workerDest}`);
      builder.log.minor(`Wrote ${dest}/routes.js`);
      builder.log.minor(`Wrote ${assetsDir} (${builder.prerendered.paths.length} prerendered pages)`);
    }
  };
}

/** @param {string} str */
function posixify(str) {
  return str.replace(/\\/g, '/');
}
