import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, BuildOptions } from 'esbuild';
import type { Adapter } from '@sveltejs/kit';
import { buildFunctionWorker } from './adapter/build-function.js';

interface AdapterOptions {
  outDir?: string;
  functions?: boolean;
  nodeCompat?: boolean;
  debug?: {
    sourcemap?: boolean;
    prettier?: boolean;
  };
}

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf-8'));
const name = '@openworkers/adapter-sveltekit';
const version: string = pkg.version;

export default function (options: AdapterOptions = {}): Adapter {
  return {
    name,
    supports: {
      read: () => true
    },

    async adapt(builder) {
      const dest = options.outDir ?? 'build';
      const assetsDir = `${dest}/assets`;
      const functionsEnabled = options.functions ?? false;
      const nodeCompat = options.nodeCompat ?? false;
      const debug = options.debug ?? {};

      const files = fileURLToPath(new URL('.', import.meta.url).href);
      const tmp = builder.getBuildDirectory('openworkers-tmp');

      builder.rimraf(dest);
      builder.mkdirp(dest);
      builder.mkdirp(assetsDir);
      builder.mkdirp(tmp);

      // Write client assets (returns list of files)
      const clientFiles = builder.writeClient(assetsDir);

      // Write prerendered pages
      builder.writePrerendered(assetsDir);

      // Separate static files from app files
      const appPath = builder.getAppPath();
      const staticFiles = clientFiles.filter((f) => !f.startsWith(appPath));

      // Generate 404.html fallback
      const fallback = path.join(assetsDir, '404.html');

      if (!existsSync(fallback)) {
        writeFileSync(fallback, 'Not Found');
      }

      // Generate manifest
      writeFileSync(
        `${tmp}/manifest.js`,
        `export const manifest = ${builder.generateManifest({ relativePath: path.posix.relative(tmp, builder.getServerDirectory()) })};\n\n` +
          `export const prerendered = new Set(${JSON.stringify(builder.prerendered.paths)});\n\n` +
          `export const base_path = ${JSON.stringify(builder.config.kit.paths.base)};\n`
      );

      // Create entry point that imports server and manifest
      const entryPoint = `${tmp}/entry.js`;
      const serverPath = posixify(path.resolve(builder.getServerDirectory(), 'index.js'));
      const manifestPath = posixify(path.resolve(tmp, 'manifest.js'));

      writeFileSync(
        entryPoint,
        `import { Server } from '${serverPath}';\n` +
          `import { manifest, prerendered, base_path } from '${manifestPath}';\n` +
          `export { Server, manifest, prerendered, base_path };\n`
      );

      // Bundle main worker with esbuild
      const workerDest = `${dest}/_worker.js`;
      const shimsDir = posixify(path.resolve(files, 'shims'));

      await build({
        entryPoints: [`${files}/runtime/worker.js`],
        bundle: true,
        format: 'esm',
        platform: 'neutral',
        mainFields: ['module', 'main'],
        outfile: workerDest,
        alias: {
          SERVER: entryPoint,
          MANIFEST: entryPoint,
          'node:async_hooks': `${shimsDir}/async-hooks.js`,
          ...(nodeCompat
            ? {
                path: `${shimsDir}/node-path.js`,
                'node:path': `${shimsDir}/node-path.js`,
                fs: `${shimsDir}/node-fs.js`,
                'node:fs': `${shimsDir}/node-fs.js`,
                url: `${shimsDir}/node-url.js`,
                'node:url': `${shimsDir}/node-url.js`
              }
            : {})
        },
        external: ['node:*'],
        minifySyntax: true,
        minifyWhitespace: true,
        minifyIdentifiers: true,
        treeShaking: true,
        banner: {
          js:
            `// Generated by ${name} v${version} at ${new Date().toISOString()}` +
            (nodeCompat ? `\nglobalThis.process = globalThis.process || { env: { NODE_ENV: "production" } };` : '')
        }
      } satisfies BuildOptions);

      // Generate mini-workers for API routes if enabled
      const functions: Array<{ pattern: string; worker: string }> = [];

      if (functionsEnabled) {
        builder.mkdirp(`${dest}/functions`);

        const serverDir = builder.getServerDirectory();
        const viteManifestPath = path.join(serverDir, '.vite/manifest.json');

        if (existsSync(viteManifestPath)) {
          const viteManifest = JSON.parse(readFileSync(viteManifestPath, 'utf-8'));
          const endpoints = extractEndpointsFromManifest(viteManifest, serverDir);

          // Resolve hooks file if the project has one
          const hooksEntry =
            viteManifest['src/hooks.server.ts'] || viteManifest['src/hooks.server.js'];

          const hooksFile = hooksEntry
            ? posixify(path.join(serverDir, hooksEntry.file))
            : undefined;

          for (const endpoint of endpoints) {
            const routePattern = endpoint.pattern;
            // Use SvelteKit route syntax for worker filename
            const workerName = endpoint.route.replace(/\//g, '-').replace(/^-/, '') || 'index';
            const workerFile = `functions/${workerName}.js`;

            // Bundle using the template with ENDPOINT alias
            await buildFunctionWorker({
              endpointFile: posixify(endpoint.file),
              outfile: `${dest}/${workerFile}`,
              routePattern: endpoint.route,
              minify: true,
              debug,
              hooksFile
            });

            functions.push({
              pattern: routePattern,
              worker: workerFile
            });

            builder.log.minor(`  Generated function: ${routePattern} → ${workerFile}`);
          }
        }
      }

      // Generate _routes.json for edge routing
      const routes = {
        // Immutable assets (hashed filenames, cache forever)
        immutable: [`/${appPath}/immutable/*`],
        // Static files from /static folder (robots.txt, favicon, etc.)
        static: staticFiles.map((f) => `/${f}`),
        // Prerendered pages (serve from assets, no worker needed)
        prerendered: builder.prerendered.paths,
        // Functions (API routes as separate workers)
        functions: functions,
        // Everything else -> SSR
        ssr: ['/*']
      };

      writeFileSync(`${dest}/_routes.json`, JSON.stringify(routes, null, 2));

      builder.log.minor(`Wrote ${workerDest}`);
      builder.log.minor(`Wrote ${dest}/_routes.json`);

      if (functions.length > 0) {
        builder.log.minor(`Wrote ${functions.length} function workers to ${dest}/functions/`);
      }

      builder.log.minor(`Wrote ${assetsDir} (${builder.prerendered.paths.length} prerendered pages)`);
    }
  };
}

interface ViteManifestEntry {
  src?: string;
  file: string;
}

interface Endpoint {
  pattern: string;
  route: string;
  file: string;
}

/**
 * Extract endpoints from Vite manifest and convert SvelteKit routes to simple patterns
 */
function extractEndpointsFromManifest(manifest: Record<string, ViteManifestEntry>, serverDir: string): Endpoint[] {
  const endpoints: Endpoint[] = [];

  for (const [key, entry] of Object.entries(manifest)) {
    // Only process endpoint files (+server.ts/js)
    if (!key.includes('+server.ts') && !key.includes('+server.js')) continue;

    const sourcePath = entry.src;
    if (!sourcePath || !sourcePath.startsWith('src/routes/')) continue;

    // Extract route from source path: src/routes/status/[code]/[[reason]]/+server.ts
    const routePart = sourcePath.replace(/^src\/routes/, '').replace(/\/\+server\.(ts|js)$/, '');

    // Convert SvelteKit route syntax to simple wildcard patterns
    const pattern = convertRouteToPattern(routePart);

    // Get the built file path
    const file = path.join(serverDir, entry.file);

    endpoints.push({
      pattern, // For routing: /status/*/*
      route: routePart, // For filename: /status/[code]/[[reason]]
      file
    });
  }

  return endpoints;
}

/**
 * Convert SvelteKit route syntax to simple wildcard patterns
 * Examples:
 *   /status/[code]/[[reason]] becomes /status/star/star
 *   /range/[n] becomes /range/star
 *   /drip/[...params] becomes /drip/doublestar
 */
function convertRouteToPattern(route: string): string {
  if (!route || route === '/') return '/';

  const segments = route.split('/').filter(Boolean);
  const patternSegments = segments.map((segment: string) => {
    // Rest parameter: [...params] -> **
    if (segment.startsWith('[...') && segment.endsWith(']')) {
      return '**';
    }

    // Required or optional parameter: [param] or [[param]] -> *
    if ((segment.startsWith('[') && segment.endsWith(']')) || (segment.startsWith('[[') && segment.endsWith(']]'))) {
      return '*';
    }

    // Static segment: keep as-is
    return segment;
  });

  return '/' + patternSegments.join('/');
}

function posixify(str: string): string {
  return str.replace(/\\/g, '/');
}
